# Generated by Django 5.0.6 on 2024-05-13 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(help_text='Имя Комании', max_length=255, verbose_name='Название')),
                ('industry', models.CharField(help_text='Промышленность', max_length=100, verbose_name='Индустрия')),
                ('address', models.CharField(help_text='Адрес компании', max_length=500, verbose_name='Адрес')),
                ('phone', models.CharField(help_text='Телефонный номер', max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(help_text='Электронная почта', max_length=254, verbose_name='Почта')),
                ('website', models.URLField(help_text='Сайт компании', verbose_name='Веб-сайт')),
                ('established_date', models.DateField(help_text='Дата основания компании', verbose_name='Дата основания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='company.company', verbose_name='Компания')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='auth.group', verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='worker', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
    ]
