# Generated by Django 5.0.6 on 2024-07-05 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('line1', models.CharField(help_text='Адрес, почтовый ящик, название компании', max_length=255, verbose_name='Адресная строка 1')),
                ('line2', models.CharField(blank=True, help_text='Квартира, офис, подразделение, здание, этаж и т.д.', max_length=255, null=True, verbose_name='Адресная строка 2')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('state_province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Штат/Провинция')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Почтовый индекс')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='amenity_icons', verbose_name='Иконка')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
            },
        ),
        migrations.CreateModel(
            name='PaidService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Платная услуга',
                'verbose_name_plural': 'Платные услуги',
            },
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='amenity_icons', verbose_name='Иконка')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Удобство комнаты',
                'verbose_name_plural': 'Удобства комнат',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('property_type', models.CharField(choices=[('house', 'Дом'), ('apartment', 'Квартира'), ('hotel', 'Отель')], max_length=20, verbose_name='Тип недвижимости')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('procent', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10)),
                ('star_rating', models.IntegerField(verbose_name='Рейтинг звёзд')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('rooms', models.IntegerField(help_text='Количество доступных комнат', verbose_name='Комнаты')),
                ('verified', models.BooleanField(default=False, verbose_name='Проверено')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.address', verbose_name='Адрес')),
                ('amenities', models.ManyToManyField(blank=True, to='properties.amenity', verbose_name='Удобства')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
            },
        ),
        migrations.CreateModel(
            name='PropertyPaidService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='Недвижимость')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.paidservice', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Платная услуга недвижимости',
                'verbose_name_plural': 'Платные услуги недвижимости',
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('photo', models.ImageField(upload_to='property_photos', verbose_name='Фото')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='Недвижимость')),
            ],
            options={
                'verbose_name': 'Фотография недвижимости',
                'verbose_name_plural': 'Фотографии недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Comment about the property', null=True, verbose_name='Коммент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property', verbose_name='Недвижимость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('room_number', models.CharField(max_length=20, verbose_name='Номер комнаты')),
                ('room_type', models.CharField(max_length=20, verbose_name='Тип комнаты')),
                ('default_price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стандартная цена за ночь')),
                ('available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('max_adults', models.IntegerField(verbose_name='Максимум взрослых')),
                ('max_children', models.IntegerField(verbose_name='Максимум детей')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='properties.property', verbose_name='Отель')),
                ('amenities', models.ManyToManyField(blank=True, to='properties.roomamenity', verbose_name='Удобства')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date_start', models.DateField(blank=True)),
                ('date_end', models.DateField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь')),
                ('rooms', models.ManyToManyField(related_name='special_prices', to='properties.room', verbose_name='Комнаты')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('photo', models.ImageField(upload_to='room_photos', verbose_name='Фото')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.room', verbose_name='Комната')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
