# Generated by Django 5.0.6 on 2024-07-22 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('icon', models.FileField(upload_to='images/categories/icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Тип недвижимости',
                'verbose_name_plural': 'Типы недвижимости',
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='roomphotos',
            options={'verbose_name': 'Фотография комнаты', 'verbose_name_plural': 'Фотографии комнат'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='procent',
        ),
        migrations.AddField(
            model_name='room',
            name='max_animals',
            field=models.IntegerField(default=1, verbose_name='Максимум животных'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(help_text='Количество комнат', verbose_name='Комнаты'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.propertytype', verbose_name='Тип недвидимости'),
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date_start', models.DateField(blank=True, verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, verbose_name='Дата окончания')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь')),
                ('rooms', models.ManyToManyField(related_name='special_prices', to='properties.room', verbose_name='Комнаты')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
