# Generated by Django 5.0.6 on 2024-05-13 08:08

import apps.business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(default=True, help_text='Активный сектор', verbose_name='Активен')),
                ('verified', models.BooleanField(default=False, verbose_name='Проверен')),
            ],
            options={
                'verbose_name': 'Сектор компании',
                'verbose_name_plural': 'Сектора компании',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('verified', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Имя документа', max_length=255, verbose_name='Имя документа')),
                ('document', models.FileField(blank=True, null=True, upload_to=apps.business.models.company_document_path, verbose_name='Документ')),
                ('upload_date', models.DateTimeField(help_text='Дата загрузки', verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(choices=[('hotel_bookings', 'Бронирование отелей'), ('car_rentals', 'Аренда автомобилей'), ('internal_tours', 'Внутренние туры'), ('international_tours', 'Международные туры'), ('medical_tours', 'Медицинские туры')], default='hotel_bookings', help_text='Выберите сектор', max_length=50, verbose_name='Название сектора')),
            ],
            options={
                'verbose_name': 'Сектор',
                'verbose_name_plural': 'Сектора',
            },
        ),
    ]
