# Generated by Django 5.0.6 on 2024-05-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysector',
            name='sector',
            field=models.CharField(choices=[('hotel_bookings', 'Бронирование отелей'), ('car_rentals', 'Аренда автомобилей'), ('internal_tours', 'Внутренние туры'), ('international_tours', 'Международные туры'), ('medical_tours', 'Медицинские туры')], default='hotel_bookings', help_text='Выберите сектор', max_length=50, verbose_name='Название сектора'),
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
