# Generated by Django 5.0.6 on 2024-07-22 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcometours',
            name='images',
        ),
        migrations.RemoveField(
            model_name='welcomecars',
            name='images',
        ),
        migrations.RemoveField(
            model_name='welcomeproperty',
            name='images',
        ),
        migrations.RemoveField(
            model_name='welcomemedicaltours',
            name='images',
        ),
        migrations.RemoveField(
            model_name='welcomeinternationaltours',
            name='images',
        ),
        migrations.CreateModel(
            name='WelcomeCarsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.welcomecars', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WelcomeInternationalToursImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.welcomeinternationaltours', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WelcomeMedicalToursImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.welcomemedicaltours', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WelcomePropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.welcomeproperty', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WelcomeToursImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.welcometours', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
