# Generated by Django 5.0.6 on 2024-07-22 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_welcometours_images_remove_welcomecars_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=123, null=True, verbose_name='Телефон')),
                ('image_desktop', models.ImageField(upload_to='images/banners/desktop/%Y/%m/', verbose_name='Картинка круп')),
                ('image_mobile', models.ImageField(upload_to='images/banners/mobile/%Y/%m/', verbose_name='Картинка моб')),
                ('page_for', models.CharField(choices=[('properties', 'Нудвижимость'), ('cars', 'Автомобили'), ('tours', 'Туры'), ('medical_tours', 'Медицинские туры')], default='provider', max_length=200, verbose_name='Страница')),
                ('link', models.URLField(blank=True, null=True, verbose_name='ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['is_active', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='welcomecarsimage',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.welcomecars', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='welcomeinternationaltoursimage',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.welcomeinternationaltours', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='welcomemedicaltoursimage',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.welcomemedicaltours', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='welcomepropertyimage',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.welcomeproperty', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='welcometoursimage',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.welcometours', verbose_name='Объект'),
        ),
    ]
