# Generated by Django 5.0.6 on 2024-07-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_retiree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='retiree_card_back',
        ),
        migrations.RemoveField(
            model_name='user',
            name='retiree_card_front',
        ),
    ]
